In [1]:
from sklearn.datasets import load_iris

In [2]:
iris_dataset=load_iris()

In [3]:
print("keys of datasets:\n{}".format(iris_dataset.keys()))

keys of datasets:
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
print(iris_dataset['DESCR'][:193]+"\n..")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
..


In [5]:
print("target names:{}".format(iris_dataset['target_names']))

target names:['setosa' 'versicolor' 'virginica']


In [6]:
print("feature:\n{}".format(iris_dataset['feature_names']))

feature:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print("types:{}".format(type(iris_dataset['data'])))

types:<class 'numpy.ndarray'>


In [8]:
print("shape:{}".format(iris_dataset['data'].shape))

shape:(150, 4)


In [9]:
print("first 5 columns of data:\n{}".format(iris_dataset['data'][:5]))

first 5 columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [10]:
print("target type:{}".format(iris_dataset['target']))

target type:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

In [13]:
print("X_train shape:{}".format(X_train.shape))
print("y_tarin shape:{}".format(y_train.shape))

X_train shape:(112, 4)
y_tarin shape:(112,)


In [14]:
print("X_test shape:{}".format(X_test.shape))
print("y_test shape:{}".format(y_test.shape))

X_test shape:(38, 4)
y_test shape:(38,)


In [15]:
import pandas as pd

In [18]:
import mglearn

In [21]:
iris_dataframe=pd.DataFrame(X_train,columns=iris_dataset.feature_names)

In [23]:
grr=pd.DataFrame.plot.scatter_matrix(iris_dataframe,c=y_train,figsize=(15,15),marker='o',hist_kwds={'bins':20},s=60,alpha=.8,cmap=mglearn.cm3)

AttributeError: type object 'PlotAccessor' has no attribute 'scatter_matrix'