In [1]:
import numpy as np

In [2]:
m=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(m)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
m=np.ones(5)
print(m)

[1. 1. 1. 1. 1.]


In [6]:
m.dtype

dtype('float64')

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])