In [3]:
import numpy as np

In [6]:
a_1d=np.array([1,2,3,4,5])
print(a_1d)

[1 2 3 4 5]


In [7]:
type(a_1d)

numpy.ndarray

In [8]:
a_1d.ndim

1

In [11]:
a_2d=np.array([[1,2,3,4],[2,3,4,5]])
print(a_2d)

[[1 2 3 4]
 [2 3 4 5]]


In [12]:
a_2d.ndim

2

In [13]:
a_2d.size

8

In [14]:
a_1d.size

5

In [15]:
a_2d.shape

(2, 4)

In [16]:
a_2d.dtype

dtype('int32')