In [2]:
import numpy as np
import random 
np.random.random(1)


array([0.88340526])

In [3]:
np.random.random((3,3))

array([[0.04992288, 0.41502176, 0.12660589],
       [0.96234297, 0.88344868, 0.32073475],
       [0.19074259, 0.05215755, 0.39082163]])

In [4]:
np.random.randint(1,4)

3

In [5]:
np.random.randint(1,4,(4,4))

array([[3, 2, 2, 1],
       [3, 2, 3, 1],
       [2, 1, 2, 3],
       [2, 3, 2, 3]])

In [6]:
np.random.randint(1,4,(2,4,4))

array([[[1, 1, 3, 1],
        [2, 2, 1, 2],
        [2, 1, 2, 2],
        [3, 2, 2, 1]],

       [[3, 3, 2, 3],
        [1, 3, 1, 3],
        [2, 1, 1, 1],
        [3, 3, 3, 3]]])

In [7]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [8]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [9]:
2**32-1

4294967295

In [10]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [11]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [13]:
np.random.randn(2,2)

array([[-1.58494101,  1.05535316],
       [-1.92657911,  0.69858388]])

In [14]:
x=[1,2,3,4]
np.random.choice(x)

3

In [15]:
np.random.choice(x)

4

In [16]:
np.random.choice(x)

1

In [17]:
np.random.choice(x)

4

In [18]:
np.random.permutation(x)

array([1, 4, 3, 2])

In [19]:
np.random.permutation(x)

array([3, 2, 1, 4])